#! /bin/bash
FLAGS=$1

ocamlopt -c bytein.ml
ocamlopt -c bytein.cmx gif.ml
ocamlopt -c bytein.cmx jpeg.ml
ocamlopt -c bytein.cmx png.ml
ocamlopt -c -I ./ bytein.cmx gif.cmx jpeg.cmx png.cmx graphicfile.ml
ocamlopt -c -a -I ./ bytein.cmx gif.cmx jpeg.cmx png.cmx graphicfile.cmx -o graphics.cmxa
