#! /bin/bash
FLAGS=$1

ocamlopt -c htmldtd.mli
ocamlopt -c htmldtd.ml
ocamlopt -c html.ml
ocamlopt -c htmldtd.cmx html.cmx htmlutil.ml
ocamlopt -a htmldtd.cmx html.cmx htmlutil.cmx -o html.cmxa

cd ./parser
./compile_ntv $FLAGS

cd ..
